import torch
import torch.nn as nn
import math
import warnings

from model.drop import DropPath
from model.DSF import DSTFormer
from einops import rearrange
from model.loss import SmoothNetLoss, SmoothL1Loss

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class MLP(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        # NOTE scale factor was wrong in my original version, can set manually to be compat with prev weights
        self.scale = qk_scale or head_dim ** -0.5

        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.proj_drop = nn.Dropout(proj_drop)


    def forward(self, x):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]
        x = self.forward_spatial(q, k, v)

        x = self.proj(x)
        x = self.proj_drop(x)
        return x

    def forward_spatial(self, q, k, v):
        B, _, N, C = q.shape
        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = attn @ v
        x = x.transpose(1, 2).reshape(B, N, C * self.num_heads)
        return x


class Block(nn.Module):

    def __init__(self, dim, num_heads, mlp_ratio=4., mlp_out_ratio=1., qkv_bias=True, qk_scale=None, drop=0.,
                 attn_drop=0.,
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)
        # NOTE: drop path for stochastic depth, we shall see if this is better than dropout here
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        mlp_out_dim = int(dim * mlp_out_ratio)
        self.mlp = MLP(in_features=dim, hidden_features=mlp_hidden_dim, out_features=mlp_out_dim, act_layer=act_layer,drop=drop)

    def forward(self, x):
        x = x + self.drop_path(self.attn(self.norm1(x)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x


class EncoderDecoder(nn.Module):
    def __init__(self, max_len, max_view, dim_feat=256, depth=2, num_heads=8, mlp_ratio=4, norm_layer=nn.LayerNorm,
                 qkv_bias=True, qk_scale=None, drop_rate=0., attn_drop_rate=0., drop_path_rate=0.):
        super().__init__()
        self.dim_feat = dim_feat
        self.st_norm = norm_layer(dim_feat)
        self.t_norm = norm_layer(dim_feat)
        self.st_embed = nn.Parameter(torch.zeros(max_view, max_len, dim_feat))
        self.t_embed = nn.Parameter(torch.zeros(max_len, dim_feat))
        trunc_normal_(self.st_embed, std=.02)
        trunc_normal_(self.t_embed, std=.02)
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks_en = nn.ModuleList([
            Block(dim=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
            for i in range(depth)])
        self.blocks_de = nn.ModuleList([
            Block(dim=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
            for i in range(depth)])

    def forward(self, x):
        B, V, F, C = x.shape
        x_res = x.clone()

        ### encoder ###
        st_embed = self.st_embed.reshape([1, V, F, self.dim_feat])
        x = self.st_norm(x + st_embed[:, 0:V, 0:F, :])
        x = rearrange(x, 'b v f c -> b (v f) c')
        for idx, blk_en in enumerate(self.blocks_en):
            x = blk_en(x)

        ### decoder ###
        x = rearrange(x, 'b (v f) c -> b v f c', v=V)
        t_embed = self.t_embed.reshape([1, 1, F, self.dim_feat])
        x = self.t_norm(x + t_embed[:, :, 0:F, :]) # 位置编码
        x = x + x_res # 残差连接
        x = rearrange(x, 'b v f c -> (b v) f c')

        for idx, blk_de in enumerate(self.blocks_de):
            x = blk_de(x)
        x = rearrange(x, '(b v) f c -> b v f c', v=V)
        return x


class FusionFormer(nn.Module):
    def __init__(self, dim_in=3, dim_out=3, dim_feat=256,
                 depth=2, num_heads=8, mlp_ratio=4,
                 num_joints=21, max_len=27, max_view=3,
                 qkv_bias=True, qk_scale=None, drop_rate=0., attn_drop_rate=0., drop_path_rate=0.,
                 norm_layer=nn.LayerNorm):
        super().__init__()
        self.dim_out = dim_out
        self.dim_feat = dim_feat
        self.joints_embed = nn.Linear(dim_in, dim_feat)
        self.pose_embed = DSTFormer(dim_in=3, dim_feat=256, dim_rep=dim_feat,
                                    depth=2, num_heads=4, mlp_ratio=2,
                                    num_joints=num_joints, maxlen=max_len)
        self.blocks = nn.ModuleList([
            EncoderDecoder(max_len=max_len, max_view=max_view,
                           dim_feat=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio,
                           qkv_bias=qkv_bias, qk_scale=qk_scale, norm_layer=norm_layer,
                           drop_rate=drop_rate, attn_drop_rate=attn_drop_rate, drop_path_rate=drop_path_rate)
            for i in range(depth)])
        self.norm = norm_layer(dim_feat)
        self.head = nn.Sequential(
            nn.Linear(dim_feat, dim_feat),
            nn.ReLU(),
            nn.Linear(dim_feat, num_joints*3),
        )
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def get_classifier(self):
        return self.head

    def forward(self, x):
        B, V, F, J, C = x.shape
        x = rearrange(x, 'b v f j c -> (b v) f j c')
        x = rearrange(self.pose_embed(x, return_rep=True), '(b v) f j c -> b v f j c', b=B)
        x = torch.mean(x, dim=-2) # B, V, F, C

        for blk in self.blocks:
            x = blk(x)

        x = rearrange(x, 'b v f c -> (b v) f c')
        x = self.head(x)
        x = x.reshape([B, V, F, J, 3])
        return x


class MotionBERTModel(nn.Module):
    def __init__(self, dim_in=3, dim_out=3, dim_feat=256,
                 depth=2, num_heads=8, mlp_ratio=4, num_joints=21, max_len=27):
        super().__init__()
        self.dim_out = dim_out
        self.dim_feat = dim_feat
        self.joints_embed = nn.Linear(dim_in, dim_feat)
        self.backbone = DSTFormer(dim_in=3, dim_feat=dim_feat, dim_rep=dim_feat,
                                  depth=depth, num_heads=num_heads, mlp_ratio=mlp_ratio,
                                  num_joints=num_joints, maxlen=max_len)
        self.joint_head = nn.Sequential(
            nn.Linear(dim_feat, dim_feat),
            nn.ReLU(),
            nn.Linear(dim_feat, 3),
        )
        self.prior_head = nn.Sequential(
            nn.Linear(dim_feat, dim_feat),
            nn.ReLU(),
            nn.Linear(dim_feat, 20),
        )
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def get_classifier(self):
        return self.head

    def forward(self, x):
        B, V, F, J, C = x.shape
        x = rearrange(x, 'b v f j c -> (b v) f j c')
        feat_out = self.backbone(x)
        joint_pos = self.joint_head(feat_out)
        joint_pos = joint_pos.reshape([B, V, F, J, 3])
        out_dict = {
            'joint':joint_pos,
            'bone':None
        }
        return out_dict

class FusionModel(nn.Module):
    def __init__(self, model_name, num_frame=15, num_joints=21, num_view=3, window_size=None, hand_prior=True, global_temporal=False):
        super().__init__()
        self.num_frame = num_frame
        self.num_joints = num_joints
        self.hand_prior = hand_prior
        self.model_name = model_name
        if model_name == 'MotionBERT':
            self.fusion_transformer = MotionBERTModel(dim_in=3, dim_feat=256, depth=2, num_heads=8, mlp_ratio=4, num_joints=num_joints, max_len=num_frame)
        else:
            raise NotImplementedError
        self.mse = nn.MSELoss()
        self.sm_loss = SmoothNetLoss(w_accel=0.1, w_pos=1)
        self.SmoothL1Loss = SmoothL1Loss()
        self.child_index = [ 1,2,3,4, 5,6,7,8, 9,10,11,12, 13,14,15,16, 17,18,19,20]
        self.parent_index = [0,1,2,3, 0,5,6,7, 0, 9,10,11,  0,13,14,15, 0, 17,18,19]

    def forward(self, inputs,  targets, meta_info):
        joints_in = inputs["joint_xyz"].cuda()
        joints_gt = targets["joint_xyz"].cuda()
        frame_center = meta_info['center_xyz'].cuda()

        B, V, F, J, _ = joints_in.size()

        val = meta_info['continuous_val'].cuda().view(B, 1, F, 1, 1) * meta_info['joint_gt_val'].cuda().view(B, 1, F, J, 1)
        val_V_repeat = val.repeat([1, V, 1, 1, 1])
        val_VP_repeat = val.repeat([1, V, 1, 1, 3])

        in_val = meta_info['joint_in_val'].cuda().reshape(B, V, F, J, 1)

        # 序列数据归一化，可能有更好的方式需要探索
        norm = 300
        frame_center = meta_info['center_xyz'].cuda()
        seq_center = torch.sum(torch.sum(frame_center*in_val, dim=2), dim=2) / (torch.sum(torch.sum(in_val, dim=2), dim=2)+1e-8)
        seq_center = seq_center.reshape([B, V, 1, 1, 3])
        joints_norm_in = (joints_in - seq_center)/norm
        joints_norm_gt = (joints_gt - seq_center)/norm

        bone_norm_pred = None
        if self.model_name == 'MotionBERT' or self.model_name == 'DDN':
            out = self.fusion_transformer(joints_norm_in)
            joints_norm_pred, bone_norm_pred = out['joint'], out['bone']
        elif self.model_name == 'TCN':
            out = self.fusion_transformer(joints_norm_in)
            joints_norm_pred, bone_norm_pred = out['joint'], out['bone']
        elif self.model_name == 'MotionAGFormer':
            out = self.fusion_transformer(joints_norm_in)
            joints_norm_pred, bone_norm_pred = out['joint'], out['bone']
        elif self.model_name == 'SmoothNet':
            smoothNet_in = rearrange(joints_norm_in, 'b v f j c -> (b v) (j c) f')
            out = self.fusion_transformer(smoothNet_in)
            joints_norm_pred = rearrange(out, '(b v) (j c) f -> b v f j c', b=B, j=J)

        # V0
        # joints_cam_pred = joints_norm_pred * norm + seq_center
        # V2
        # joints_cam_pred = (joints_norm_pred + 1) / 2 * (joints_temp_max - joints_temp_min) + joints_temp_min + seq_center
        # V4
        joints_cam_pred = joints_norm_pred * norm + seq_center

        if self.training:
            joint_loss = self.sm_loss(joints_norm_pred.reshape(B * V, F, J * 3), joints_norm_gt.reshape(B * V, F, J * 3), 1 - val_VP_repeat.view(B * V, F, J * 3))
            joint_error = self.calculate_error(joints_cam_pred.reshape(B * V, F, J, 3), joints_gt.reshape(B * V, F, J, 3), val_V_repeat.view(B * V, F, J, 1))
            joint_error_init = self.calculate_error(joints_in.reshape(B * V, F, J, 3), joints_gt.reshape(B * V, F, J, 3), val_V_repeat.view(B * V, F, J, 1))
            out = {'pd_joint_xyz': joints_cam_pred.reshape(B, V, F, J, 3)}
            loss = {'joint_loss': joint_loss}
            error = {'init': joint_error_init, 'refine': joint_error}
            if bone_norm_pred is not None:
                bone_norm_gt = joints_norm_gt.reshape(B * V, F, J, 3)[..., self.parent_index, :] - joints_norm_gt.reshape(B * V, F, J, 3)[..., self.child_index, :]
                bone_val = (val_V_repeat[..., self.parent_index, :] + val_V_repeat[..., self.child_index, :]).eq(2).float()
                bone_norm_len_gt = torch.sqrt(torch.sum(bone_norm_gt * bone_norm_gt, dim=-1))
                bone_norm_avg_len_gt = torch.sum(bone_norm_len_gt * bone_val.view(B * V, F, 20), dim=1) / (torch.sum(bone_val.view(B * V, F, 20), dim=1) + 1e-8)
                bone_loss = self.SmoothL1Loss(bone_norm_pred, bone_norm_avg_len_gt.view(B, V, 20))
                loss['bone_loss'] = bone_loss
            return out, loss, error
        else:
            out = {'pd_joint_xyz': joints_cam_pred}
            return out

    def get_vec(self, joint):
        b, t, j, c = joint.size()
        vec = joint[:, 1:, :, :] - joint[:, 0:-1, :, :]
        vec = torch.sqrt(torch.sum(vec*vec, dim=-1))
        return vec

    def get_acc(self, joint):
        vec = self.get_vec(joint)
        acc = vec[:, 1:, ...] - vec[:, 0:-1, ...]
        return acc

    def calculate_error(self, joint, gt, val):
        diff = (joint*val - gt*val)
        error = torch.sqrt(torch.sum(diff*diff, dim=-1))
        return error.sum() / (val.sum() + 1e-8)

    def calculate_acc_error(self, joint, gt, val):
        pd_acc = self.get_acc(joint)
        gt_acc = self.get_acc(gt)
        acc_error = torch.mean(torch.abs(pd_acc - gt_acc) * val) / (val.mean() + 1e-8)
        return acc_error


if __name__ == '__main__':
    # B,V,F,J = 8, 3, 15, 21
    # input_joint = torch.rand([B,V,F,J,3]).cuda()
    # model = FusionModel(num_frame=F, num_joints=J, num_view=V).cuda()
    # out = model(input_joint)
    # print(out.size())

    B, V, F, J = 8, 3, 25, 21
    in_joint = torch.rand(B, V, F, J, 3).float().cuda()
    gt_joint = torch.rand(B, V, F, J, 3).float().cuda()
    center = torch.ones(B, V, F, 1, 3).float().cuda()
    in_joint_val = torch.ones([B, V, F, 21]).float().cuda()
    gt_joint_val = torch.ones([B, 1, F, 21]).float().cuda()
    continuous_val = torch.ones([B, F, 1]).float().cuda()
    inputs = {'joint_xyz':in_joint}
    targets = {'joint_xyz':gt_joint}
    meta_info = {"center_xyz": center,
                 'continuous_val': continuous_val,
                 'joint_gt_val': gt_joint_val,
                 'joint_in_val': in_joint_val
                 }
    model = FusionModel('DDN', num_frame=F, num_joints=J, num_view=V, global_temporal=True).cuda().eval()
    out = model(inputs, targets, meta_info)
    print(out['pd_joint_xyz'].size())
    # print(out['pd_joint_xyz'].size())
    # print(error['acc_init'])
    # print(error['init'])